[project]
name = "shapenetdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open-clip-torch>=3.0.0",
    "open3d>=0.19.0",
    "plyfile>=1.1.2",
    "vectordb>=0.0.21",
]
